### ISSUE TITLE
What's Etherium ?

### ISSUE THREAD

**Issue by mortimr** [noeRls/ethereumWalletSeeker#1]
![screen shot 2018-07-28 at 9 51 03 pm](https://user-images.githubusercontent.com/17824082/43360142-5bffb36e-92b0-11e8-8e28-0eecfeac326f.png)

Never heard of this project before :/
Maybe you're talking about Ethereum ?

Also this [link](https://bitcoin.stackexchange.com/a/21648) might be interesting for you :)

**Comment by noeRls** [comment]
Yea it's about Ethereum, i made a typo in the repository name, i just fixed it :).

I made this project when i started to work on blockchain. I was so surprised that the only security of a wallet was that there was too much possibility to generate an existing one.
The goal of this project is to know how fast you can "verify" wallet and generate it. Nowadays it can only test an average of 2000 wallet per second. So yea the chance to find a wallet with some eth in is close to 0%
